block-sizes:
  - 128k
write-mixes:
  - 100
total-logs:
  - 1
  - 2
  - 4
  - 6
  - 8
  - 12
  - 16
  - 20
  - 25
  - 30
  - 35
  - 40
  - 45
  - 50
leader-logs:
  - 90
  - 80
  - 70
  - 60
  - 65
  - 55
  - 50
  - 45
  - 40
  - 35
  - 30
  - 20
  - 10
data-directory: /media/disk1
rate-process: poisson
fio-path: /usr/local/bin/fio
